lab02/encuesta/urls.py
from django.urls import path 

from . import views

app_name = 'encuesta'

urlpatterns = [
    path('', views.index, name='index'),
    path('enviar', views.enviar, name='enviar'),
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('encuesta/', include('encuesta.urls')),
    path('operaciones/', include('operaciones.urls')),
    path('volumencilindro/', include('volumencilindro.urls')),
]

lab02/operaciones/urls.py
from django.urls import path 

from . import views

app_name = 'operaciones'

urlpatterns = [
    path('', views.index, name='index'),
    path('enviar_op', views.enviar_op, name='enviar_op'),
]

lab02/volumencilindro/urls.py
from django.urls import path 

from . import views

app_name = 'volumencilindro'

urlpatterns = [
    path('', views.index, name='index'),
    path('enviar_vol', views.enviar_vol, name='enviar_vol'),
]

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/operaciones/models.py
from django.db import models

# Create your models here.

lab02/volumencilindro/models.py
from django.db import models

# Create your models here.

lab02/encuesta/views.py
from django.shortcuts import render

def index(request):
    context = {
        'titulo' : "Formulario",
    }
    return render(request, 'encuesta/formulario.html', context)
def enviar (request):
    context = {        
        'titulo': "Respuesta",
        'nombre': request.POST['nombre'], 
        'clave': request.POST['password'],
        'educacion': request. POST['educacion'],
        'nacionalidad': request.POST['nacionalidad'],
        'idiomas' : request.POST.getlist('idiomas'),
        'correo': request.POST['email'],
        'website': request.POST['sitioweb'],
    }
    return render(request, 'encuesta/respuesta.html', context)

lab02/operaciones/views.py
from django.shortcuts import render

def index (request):
    context = {
        'titulo' : "Operaciones basicas",
    }
    return render( request, 'operaciones/formulario.html', context)

def enviar_op (request):
    operacion = request.POST['operacion']
    numero1 = float(request.POST['numero1'])
    numero2 =  float(request.POST['numero2'])
    match operacion:
        case "suma":
            resultado = numero1 + numero2
        case "resta":
            resultado = numero1 - numero2
        case "multiplicacion": 
            resultado = numero1 * numero2 
        case _:
            resultado = 0
    context = {        
        'titulo': "Respuesta",
        'operacion' : operacion,
        'numero1': numero1, 
        'numero2': numero2,
        'resultado' : resultado,
    }
    return render(request, 'operaciones/respuesta.html', context)

lab02/volumencilindro/views.py
from django.shortcuts import render
import math

def index (request):
    context = {
        'titulo' : "Calcular el volumen del cilindro",
    }
    return render( request, 'volumencilindro/formulario.html', context)

def enviar_vol (request):
    diametro = float(request.POST['diametro'])
    altura =  float(request.POST['altura'])
    resultado = (math.pi*(diametro/2)**2)*(altura)
    context = {        
        'titulo': "Respuesta",
        'diametro': diametro, 
        'altura': altura,
        'resultado' : resultado,
    }
    return render(request, 'volumencilindro/respuesta.html', context)

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>
    Contraseña:
    <input type="password" name="password"><br>
    Educacion:
    <select name="educacion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="educacion-obligatoria" selected="selected">Educación Obligatoria</option>
        <option value="formacion-profesional">Formación profesional</option> 
        <option value="universidad">Universidad</option>
    </select> <br>    
            Nacionalidad:
            <input type="radio" name="nacionalidad" value="hispana">Hispana</input>
            <input type="radio" name="nacionalidad" value="otra">Otra</input><br> 
            Idiomas:
            <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input> 
            <input type="checkbox" name="idiomas" value="inglés">Inglés</input>
            <input type="checkbox" name="idiomas" value="francés">Francés</input>
            <input type="checkbox" name="idiomas" value="aleman">Alemán</input><br> 
            Email:
            <input type="text" name="email"><br>
            Sitio Web:
            <input type="text" name="sitioweb"><br>
            <input type="submit" name="submit" value="Enviar">
</form>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }}</h2>
<p>Nombre: {{ nombre }}</p>
<p>Educacion: {{ clave }}</p>
<p>Educacion: {{ educacion }}</p>
<p>Nacionalidad: {{ nacionalidad }}</p>
<p>Idiomas: </p>
<ul>
    {% for item in idiomas %}
    <li>{{item}}</li>
    {% endfor %}
</ul>
<p>Email: {{correo}} </p>
<p>Sitio Web: {{ website }}</p>

lab02/operaciones/templates/operaciones/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'operaciones:enviar_op' %}" method="post">
    {% csrf_token %}
    Primer numero::
    <input type="number" name="numero1" required><br>
    Segundo numero:
    <input type="number" name="numero2" required><br>
    Educacion:
    <select name="operacion">
        <option value="suma" selected="selected">Suma</option>
        <option value="resta" >Resta</option>
        <option value="multiplicacion">Multiplicacion</option> 
    </select> <br>    
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/operaciones/templates/operaciones/respuesta.html
<h2>{{ titulo }}</h2>
<p>El primer numero elegido es: {{ numero1 }}</p>
<p>El segundo numero elegido es: {{ numero2 }}</p>
<p>El resultado de la {{ operacion }} es {{ resultado }}</p>

lab02/volumencilindro/templates/volumencilindro/formulario.html
<h2>{{ titulo }}</h2> <br>
<form action="{% url 'volumencilindro:enviar_vol' %}" method="post">
    {% csrf_token %}
    Introduzca el diametro en metros:
    <input type="number" name="diametro" required><br>
    Introduzca la altura en metros:
    <input type="number" name="altura" required><br>
    <input type="submit" name="submit" value="Calcular">
</form>

lab02/volumencilindro/templates/volumencilindro/respuesta.html
<h2>{{ titulo }}</h2>
<p>El diametro elegido fue de: <strong>{{ diametro }} metro(s)</strong></p>
<p>La altura elegida fue de: <strong>{{ altura }} metro(s)</strong></p>
<p>El volumen del cilindro es de <strong> {{ resultado }} metros cubicos </strong></p>